env:
  ARTIFACTORY_REPOSITORY: 'knolar-npm'
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:
    name: Build, Test, and Deploy Npm Package
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm set virtual repository
      run: |
        npm config set //cepsa.jfrog.io/artifactory/api/npm/${{ env.ARTIFACTORY_REPOSITORY }}/:_authToken ${{ secrets.ARTIFACTORY_TOKEN }}

    - name: npm install
      run: |
        npm install --production

    - name: npm build
      run: |
        npm run build --if-present

    - name: npm test
      run: |
        npm run test --if-present

    - name: SonarQube Scan
      uses: Cloud-Process-History/devops-sonarqube-scan-action@1.0
      with:
        host: ${{ secrets.SONAR_HOST }} 
        login: ${{ secrets.SONAR_USER }}   
        password: ${{ secrets.SONAR_PWD }}   

    - name: npm publish
      run: |
        npm publish

