name: New Python Artifact Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_GENERIC_REPOSITORY: 'knolar-generic'
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    
    - name: Install dependencies
      run: |
        cd ${GITHUB_WORKSPACE}/src
        pip install setuptools wheel twine tox -i https://${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_PWD }}@cepsa.jfrog.io/artifactory/api/pypi/${{ ARTIFACTORY_REPOSITORY }}/simple
        pip install -r ${GITHUB_WORKSPACE}/src/requirements.txt -i https://${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_PWD }}@cepsa.jfrog.io/artifactory/api/pypi/${{ env.ARTIFACTORY_PYTHON_REPOSITORY }}/simple

    - name: Run tests
      run: |
        tox
    
    - name: SonarQube Scan
      uses: Cloud-Process-History/github-action-sonarqube-scan@1.0
      with:
        host: ${{ secrets.SONAR_HOST }} 
        login: ${{ secrets.SONAR_USER }}   
        password: ${{ secrets.SONAR_PWD }}        
    
    - name: Publish
      run: |

        mkdir ${GITHUB_WORKSPACE}/dist
        cp -r ${GITHUB_WORKSPACE}/src/* ${GITHUB_WORKSPACE}/dist
        cd ${GITHUB_WORKSPACE}/dist
        
        pip install -r ${GITHUB_WORKSPACE}/dist/requirements.txt -t ${GITHUB_WORKSPACE}/dist/lambda -i https://${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_PWD }}@cepsa.jfrog.io/artifactory/api/pypi/${{ env.ARTIFACTORY_PYTHON_REPOSITORY }}/simple

        # generate zip package        
        PACKAGE_VERSION=$(python setup.py --version)
        PACKAGE_NAME=$(python setup.py --name)

        zip -r ${GITHUB_WORKSPACE}/${PACKAGE_NAME}-${PACKAGE_VERSION}.zip *

        # calculate checksums
        sha256=$(openssl dgst -sha256 ${GITHUB_WORKSPACE}/${PACKAGE_NAME}-${PACKAGE_VERSION}.zip|sed 's/^SHA256.*= //')
        sha1=$(openssl dgst -sha1 ${GITHUB_WORKSPACE}/${PACKAGE_NAME}-${PACKAGE_VERSION}.zip|sed 's/^SHA.*= //')

        # upload zip
        curl -u ${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_PWD }} \
             -sS -T ${GITHUB_WORKSPACE}/${PACKAGE_NAME}-${PACKAGE_VERSION}.zip \
             -H "X-Checksum-Sha256:${sha256}" -H "X-Checksum-Sha1:${sha1}" \
             "https://cepsa.jfrog.io/artifactory/${{ env.ARTIFACTORY_GENERIC_REPOSITORY }}/${PACKAGE_NAME}/${PACKAGE_NAME}-${PACKAGE_VERSION}.zip"