name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        cd ${GITHUB_WORKSPACE}/src
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Run tests
      run: |
        python -m pip install --upgrade pip
        pip install tox && tox
    # TODO
    #- name: SonarQube Scan
    #  uses: cepsadigital/devops-sonar-github-action@master
    #  with:
    #    host: https://sonar.devops.cepsacorp.com
    #    login: ${{ secrets.SONARQUBE_TOKEN }}        
    - name: Build and publish
      run: |
        cd ${GITHUB_WORKSPACE}/src
        python setup.py sdist bdist_wheel
        twine upload --repository-url https://cepsa.jfrog.io/artifactory/api/pypi/knolar-python -u ${{ secrets.ARTIFACTORY_USER }} -p ${{ secrets.ARTIFACTORY_PWD }} --non-interactive dist/*