name: New Repository Created

on:
  workflow_dispatch:
    inputs:
      event_type:
        description: 'Event Type'
        required: true
        default: created
      repository_path:
        required: true
        default: Cloud-Process-History/test-hook

jobs:
  greeting:
    runs-on: ubuntu-latest
    #permissions:
    #  issues: write
    env:
      GITHUB_TOKEN: ${{ secrets.ROBOT_TOKEN }}
    steps:
      - name: Github CLI Login
        run: |
          gh --version
          echo ${GITHUB_TOKEN} >> token.txt
          gh auth login --with-token < token.txt

      - name: Clone repo
        run: |
          gh repo clone repository_path


    #- uses: actions/first-interaction@v1
    #  with:
    #    repo-token: ${{ secrets.GITHUB_TOKEN }}
    #    issue-message: 'Message that will be displayed on users first issue'
