name: New Repository Created

on:
  workflow_dispatch:
    inputs:
      event_type:
        description: 'Event Type'
        required: true

jobs:
  greeting:
    runs-on: ubuntu-latest
    #permissions:
    #  issues: write
    steps:
      - name: Github CLI
        run: |
          gh --version

    #- uses: actions/first-interaction@v1
    #  with:
    #    repo-token: ${{ secrets.GITHUB_TOKEN }}
    #    issue-message: 'Message that will be displayed on users first issue'
